// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzEoRw2CMn5xnq1CfM5MoccVq52Q8mTqU',
    appId: '1:681070215434:web:faef721690c54c78433af3',
    messagingSenderId: '681070215434',
    projectId: 'sshhotels-724c1',
    authDomain: 'sshhotels-724c1.firebaseapp.com',
    storageBucket: 'sshhotels-724c1.firebasestorage.app',
    measurementId: 'G-YKV15C5CVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDLPRwF05f77vlJ1F3JbJ2Ek8TTTCs2Qc',
    appId: '1:681070215434:android:bf0d50fa0069d992433af3',
    messagingSenderId: '681070215434',
    projectId: 'sshhotels-724c1',
    storageBucket: 'sshhotels-724c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCurln1XTHOV0NIhjx2h6-fKPVq1o24j2Y',
    appId: '1:681070215434:ios:681119a2de767200433af3',
    messagingSenderId: '681070215434',
    projectId: 'sshhotels-724c1',
    storageBucket: 'sshhotels-724c1.firebasestorage.app',
    iosBundleId: 'com.example.sshCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCurln1XTHOV0NIhjx2h6-fKPVq1o24j2Y',
    appId: '1:681070215434:ios:681119a2de767200433af3',
    messagingSenderId: '681070215434',
    projectId: 'sshhotels-724c1',
    storageBucket: 'sshhotels-724c1.firebasestorage.app',
    iosBundleId: 'com.example.sshCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzEoRw2CMn5xnq1CfM5MoccVq52Q8mTqU',
    appId: '1:681070215434:web:ac76399e0daf1361433af3',
    messagingSenderId: '681070215434',
    projectId: 'sshhotels-724c1',
    authDomain: 'sshhotels-724c1.firebaseapp.com',
    storageBucket: 'sshhotels-724c1.firebasestorage.app',
    measurementId: 'G-KBL57TXF18',
  );
}
